# Generated by Django 5.0.6 on 2025-08-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='nutrition_info',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
