# Generated by Django 5.0.6 on 2025-08-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_nutrition_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='prepTime',
            field=models.TextField(blank=True, null=True),
        ),
    ]
